name: shorebird_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shorebird_code_push: ^1.1.6
  flutter_riverpod: ^2.6.1
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true